### ISSUE TITLE
AutoCombine looses focus after having unloaded

### ISSUE THREAD

**Issue by Mogli12** [Mogli12/AutoCombine#1]
### Received via PN from Vogn22 on modhoster.de

Unfortunately, in my testing I have found another bug: The combine VERY OFTEN looses focus (state changes from green to white) after having unloaded or, after I have selected / deselected the combine.

This morning I realised that my use of a GamePad for controlling the vehicles might be part of the problem, since I may "shake" the steering joystick a little, when I press the buttons assigned to switch between vehicles. Using TAB or Shift+TAB on the keyboard is safer, it seems. I will experiment with the "deadzone" of the joystick to see if it makes things better.

However, that does not explain, that the combine looses focus in the moment it continues harvesting after an unload I standing mode. I have used the built-in Bjornholm map for the testing and I had no other mods installed. I harvested field 29 with the C6 combine and field 22 with the big Case combine. I unloaded A LOT and I saw this new(?) problem several times. Actually, I'm not sure that it never happened before, but I used to think of AutoCombine as a very reliable mod.

Another thought just passed my mind: Maybe I push the combine just a little out of its position with the tipper, when I approach the combine that has stopped 5 meters from my tipper? Could be the reason...

**Comment by ghost** [comment]
Since last time I wrote, I have experimented with AutoCombine 4.1 and AutoCombine 3.2 as well. I am absolutely certain, that the problem is related to the use of GamePad. If I disconnect that from the computer, there is no problem with AutoCombine - it's only harder to drive the tractor :-) Also, the 3.2 version does not have the problem (but 3.2 has a problem with unloading in stopped mode, which is solved in version 4.1).
At some stage in my testing, I got the bright idea to clear the InputBinding.xml. After that, the problem disappeared! But restoring the old InputBinding.xml did not bring the problem back. Should be solved then? Nah, trying AutoCombine 4.1 on a different map with multiple combines brought the problem back - partly.
For now, to my best knowledge, there IS a problem with AutoCombine 4.1 when using GamePad and when "passing" by the combine(s) using TAB / Shift+TAB or whatever (GamePad) key you have assigned to the "switch tractor" function. It looks like the problem no longer occurs when the combine unloads "undisturbed" by human.

**Comment by Mogli12** [comment]
After stopping (e.g. unloading) the combine will drive back a bit. I changed the way the direction for this operation is calculated. Does this fix your problem?

**Comment by ghost** [comment]
I like the idea of reversing the combine a little. It will probably solve a different and much smaller problem: Sometimes the combine skips a little of the crops when resuming the harvest after unload.
However, my major issue is the bad influence a GamePad has on AutoCombine and that has not been solved. When I switch between vehicles, using the GamePad keys I have assigned to "Switch tractor", I very often send the combine off track, as shown on the included screenshot. It may also  happen when I use TAB on the keyboard. If it only happened when switching TO a combine, the problem would be copeable, since you immediately see, that the title "AutoCombine v4.1 b1" switches to white. However, it also happens when you switch AWAY FROM a combine and then you have an uncontrolled combine wandering off in the field, as shown on the second screenshot.
![fsscreen_2015_09_18_07_42_20](https://cloud.githubusercontent.com/assets/13365416/9953137/489ff432-5dde-11e5-9a32-41cb072ae291.png)
![fsscreen_2015_09_18_08_08_40](https://cloud.githubusercontent.com/assets/13365416/9953341/380802b6-5de0-11e5-941b-bb7c480f2da4.png)

**Comment by Mogli12** [comment]
I think that moving away from a combine is the hint I was missing. I guess I have identified and fixed the problem.

**Comment by ghost** [comment]
I expect to test it further during the weekend, but I can already say: MUCH better!

**Comment by ghost** [comment]
I have now spent several hours harvesting barley with 7 combines and 7 trucks. I have not seen the combines loosing focus when I switch AWAY from them. AutoCombine 4.1 has thereby become much better than it was. Thanks!
There are still two cases, where AutoCombine SOMETIMES looses focus: When you move TO the combine and when you START the hired worker of AutoCombine. (I may not have mentioned the latter before, but it has been like that all the time.) In these two cases, however, you are still supervising the hired worker (read: having control of the combine in question), and you can immediately see, that focus is lost, because the "AutoCombine v4.1" text changes to (or remains) white. All you have to do, is a little steering, in order to get the combine on the right track. Therefore, these errors are not critical.
Furthermore, it seems that you have fixed the problem we discussed long ago, about the combine stopping too early, when there is a tipper waiting for it. Great!
And finally: It's a bright idea to show the "AutoCombine v4.1" text even when the dialog box is closed.

**Comment by Mogli12** [comment]
It is now possible to turn off the manual steering with the key combination KEY_lalt KEY_6. This is why I will close this issue for now.
